ministryofjustice/hmpps-adjustments

integration_tests/e2e/rada.cy.ts
server/model/adjustmentTypes.ts
server/model/viewModel.ts
server/routes/adjustmentRoutes.test.ts
server/views/pages/adjustments/view.njk

https://github.com/ministryofjustice/hmpps-adjustments/assets/3595969/667c6fdf-c303-44b9-9397-edf488003f55

ADJUST1-86 Add total row to adjustment details table

---

server/@types/adjustments/index.d.ts
server/model/adjustmentFormFactory.ts
server/model/adjustmentTypes.ts
server/model/reviewModel.ts
server/model/ualType.ts
server/model/unlawfullyAtLargeForm.ts
server/utils/utils.test.ts
server/utils/utils.ts
server/views/pages/adjustments/form.njk
server/views/pages/adjustments/unlawfullyAtLarge.njk

TODO:
- Edit journey
- Validation
https://github.com/ministryofjustice/hmpps-adjustments/assets/3595969/7ce8118a-c77e-4320-9711-49666a269bba

ADJUST1-69 Add UAL journey (create)

---

scripts/generate-adjustment-types.sh
server/@types/adjustments/index.d.ts
server/routes/adjustmentRoutes.test.ts
server/views/pages/adjustments/review.njk

https://github.com/ministryofjustice/hmpps-adjustments/assets/3595969/f8a16ec0-07b8-4c28-bee2-4afa3c1f0c0e

ADJUST1-67 Change 'Cancel' button on review screen to be 'Edit'

---

integration_tests/e2e/rada.cy.ts
integration_tests/mockApis/adjustmentsApi.ts
integration_tests/pages/hub.ts
server/model/adjustmentsHubViewModel.ts
server/model/hubValidationMessages.ts
server/routes/adjustmentRoutes.test.ts
server/routes/adjustmentRoutes.ts
server/views/pages/adjustments/hub.njk

https://github.com/ministryofjustice/hmpps-adjustments/assets/3595969/06fb8133-d294-4ff0-a20b-c9be580bdd1b

ADJUST1-85 Add rada validation, only allow entry into the add screen if there exist ADAs

---

server/routes/additionalDaysAwardedRoutes.ts
server/services/additionalDaysAwardedService.ts
server/services/index.ts

Could potentially cache the system token (similar to activities) - to discuss with @joelstobart-moj first

ADJUST1-180 Use system token to call adjudication api

---

server/@types/AdaTypes.ts
server/services/additionalDaysAwardedService.test.ts
server/services/additionalDaysAwardedService.ts

ADJUST1-47 Determine consecutive / concurrent ADAs and label accordingly for ADA review screen

---

server/views/macros/adaTable.njk

ADJUST1-240 Add total row for each charge - showing total number of ADAs per charge

---

server/model/remandViewModel.ts
server/routes/index.ts
server/routes/remandRoutes.ts
server/views/pages/adjustments/remand/view.njk

ADJUST1-281 Add initial view remand screen

---

server/@types/prisonApi/prisonClientTypes.ts
server/model/remandRemoveModel.ts
server/routes/index.ts
server/routes/remandRoutes.test.ts
server/routes/remandRoutes.ts
server/views/pages/adjustments/remand/remove.njk
server/views/pages/adjustments/remand/view.njk

https://github.com/ministryofjustice/hmpps-adjustments/assets/3595969/a39438c7-95fe-42d9-a36a-7a3b1f41fed1

ADJUST1-255 Add remove remand screen and POST functionality

---

integration_tests/e2e/remand.cy.ts
integration_tests/pages/form.ts
integration_tests/pages/hub.ts
integration_tests/pages/remandSelectOffences.ts
integration_tests/pages/reviewRemand.ts
integration_tests/pages/saveRemand.ts
integration_tests/pages/viewRemand.ts
server/model/remandReviewModel.ts
server/views/pages/adjustments/remand/dates.njk

TODO:  enhance tests (screens are undergoing redesign)

ADJUST1-318 Add initial cypress tests for Remand journey (WIP and screens to be changed)

---

.gitignore
server/model/taggedBailSelectCaseModel.ts
server/routes/index.ts
server/routes/taggedBailRoutes.test.ts
server/routes/taggedBailRoutes.ts
server/views/pages/adjustments/tagged-bail/select-case.njk

ADJUST1-321 Add first screen for add tagged bail journey

---

server/model/taggedBailDaysForm.ts
server/model/taggedBailDaysModel.ts
server/model/taggedBailReviewModel.ts
server/routes/index.ts
server/routes/taggedBailRoutes.test.ts
server/routes/taggedBailRoutes.ts
server/views/pages/adjustments/tagged-bail/days.njk
server/views/pages/adjustments/tagged-bail/review.njk

ADJUST1-323 Add the first version of the confirm-and-save screen for tagged bail

---

server/model/taggedBailDaysForm.ts
server/model/taggedBailDaysModel.ts
server/model/taggedBailReviewModel.ts
server/model/taggedBailSelectCaseModel.ts
server/routes/index.ts
server/routes/taggedBailRoutes.test.ts
server/routes/taggedBailRoutes.ts
server/views/pages/adjustments/tagged-bail/days.njk
server/views/pages/adjustments/tagged-bail/review.njk
server/views/pages/adjustments/tagged-bail/select-case.njk

https://github.com/ministryofjustice/hmpps-adjustments/assets/3595969/f6a67b39-c68e-4e7d-ba93-ce4cd0b25c3a

ADJUST1-362 When creating a new tagged-bail - allow editing of details

---

server/model/remandReviewModel.ts
server/routes/remandRoutes.test.ts
server/views/pages/adjustments/remand/partials/remandOffence.njk
server/views/pages/adjustments/remand/review.njk

Renamed labels // Removed bullet points from offences // Added total days component to review screen

ADJUST1-450 DR: Review remand details

---

integration_tests/e2e/ada.cy.ts
integration_tests/e2e/rada.cy.ts
server/model/adjustmentsHubViewModel.ts
server/routes/additionalDaysAwardedRoutes.ts
server/routes/adjustmentRoutes.test.ts
server/routes/adjustmentRoutes.ts
server/routes/remandRoutes.test.ts
server/routes/remandRoutes.ts
server/routes/taggedBailRoutes.test.ts
server/routes/taggedBailRoutes.ts
server/views/pages/adjustments/hub.njk

This reverts commit c294cc372ffe47e2a35a5af9f9b16ed822a72da0.

Revert "ADJUST1-495 DR: UAL banner (#219)"

---

server/model/adjustmentFormFactory.ts
server/model/adjustmentTypes.ts
server/model/lalAffectsReleaseDates.ts
server/model/lawfullyAtLargeForm.ts
server/routes/adjustmentRoutes.test.ts
server/views/pages/adjustments/lawfullyAtLarge.njk

* Also test the edit page for lawfully at large to avoid future refactoring.

ADJST-750 Create add page for Lawfully at Large

---

server/model/remandReviewModel.ts

The nowrap tag was being read announced by the screen reader. The nowrap tag is only required where the text will be visible.

ADJST-826 Remove nowrap date from hidden text.

---

integration_tests/e2e/unlawfullyAtLarge.cy.ts
integration_tests/mockApis/adjustmentsApi.ts
integration_tests/pages/hub.ts
integration_tests/pages/unlawfullyAtLarge/removeUnlawfullyAtLarge.ts
integration_tests/pages/unlawfullyAtLarge/reviewUnlawfullyAtLarge.ts
integration_tests/pages/unlawfullyAtLarge/unlawfullyAtLargeFormPage.ts
integration_tests/pages/unlawfullyAtLarge/viewUnlawfullyAtLarge.ts

Adding E2E Cypress test cases for unlawfully-at-large journey,

ADJST-944 End to end test of Unlawfully at Large

---

server/@types/AdaTypes.ts
server/@types/adjustments/index.d.ts
server/views/pages/adjustments/additional-days/intercept.njk
server/views/pages/adjustments/additional-days/review-and-approve.njk

Reverts ministryofjustice/hmpps-adjustments#459

Revert "Code to align APIs for TECH ANALYSIS 1 in ADJST-953"

---

server/@types/AdaTypes.ts
server/@types/adjustments/index.d.ts
server/views/pages/adjustments/additional-days/intercept.njk
server/views/pages/adjustments/additional-days/review-and-approve.njk

Reverts ministryofjustice/hmpps-adjustments#464

Revert "Revert "Code to align APIs for TECH ANALYSIS 1 in ADJST-953""

---

server/routes/hubRoutes.test.ts
server/views/partials/thingsToDoPanel.njk

Update to title as per screenshots - https://dsdmoj.atlassian.net/browse/ADJST-870

Bug Fix for Things To Do panel title

---

helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml

Switching off the ADA intercept page as we are switching on the things to do panel.
This is for pre-prod and prod.
https://github.com/ministryofjustice/hmpps-court-cases-release-dates-api/pull/18

Toggle On - Things To Do

---

assets/scss/application.scss
server/model/viewModel.ts

https://dsdmoj.atlassian.net/browse/ADJST-1040

ADJST-1040 Design fix to avoid overlapping Edit and Delete buttons

---

helm_deploy/values-dev.yaml

https://dsdmoj.atlassian.net/browse/ADJST-404
https://github.com/ministryofjustice/cloud-platform-environments/pull/29929

ADJST-404 Add another dns name

---

server/routes/additionalDaysAwardedRoutes.test.ts
server/views/pages/adjustments/additional-days/review-and-approve.njk

https://dsdmoj.atlassian.net/browse/ADJST-1117

ADJST-1117 Change message for ADAs to be approved

---

server/model/unlawfully-at-large/unlawfullyAtLargeForm.ts
server/routes/adjustmentRoutes.test.ts
server/routes/adjustmentRoutes.ts

https://dsdmoj.atlassian.net/browse/ADJST-957

Adjst 957 - UAL Date overlap validation

---

helm_deploy/hmpps-adjustments/values.yaml

https://dsdmoj.atlassian.net/browse/ADJST-513

ADJST-513 Add missing env variable

---

helm_deploy/values-dev.yaml

https://dsdmoj.atlassian.net/browse/ADJST-404

ADJST-404 Move to new ingress url

---

esbuild/esbuild.config.js
server/middleware/setUpStaticResources.ts
server/views/pages/adjustments/additional-days/review-prospective.njk
server/views/partials/layout.njk

https://dsdmoj.atlassian.net/browse/ADJST-1002

ADJST-1002 Fix css issue for ESBuild

---

assets/js/index.js
server/middleware/supportUserReadonlyMiddleware.ts
server/views/partials/layout.njk

https://dsdmoj.atlassian.net/browse/ADJST-1002

ADJST-1002 Correcting JS imports and Adding logging statement for support user

---

server/views/pages/adjustments/hub.njk

https://dsdmoj.atlassian.net/browse/ADJST-1135

ADJST-1135 Design changes - Alignments

---

server/views/pages/adjustments/hub.njk

https://dsdmoj.atlassian.net/browse/ADJST-1135

ADJST-1135 Design fixes

---

server/views/pages/adjustments/appeal-applicant/days.njk
server/views/pages/adjustments/custody-abroad/days.njk
server/views/pages/adjustments/restoredAdditionalDays.njk
server/views/pages/adjustments/special-remission/days.njk
server/views/pages/adjustments/tagged-bail/days.njk

https://dsdmoj.atlassian.net/browse/ADJST-1137

ADJST-1137 - Remove suffix days as part of design review

---

server/views/pages/adjustments/appeal-applicant/offences.njk

https://dsdmoj.atlassian.net/browse/ADJST-1138

ADJST-1138 - Change to two-thrird width instead of full

---

server/views/pages/adjustments/custody-abroad/offences.njk

https://dsdmoj.atlassian.net/browse/ADJST-1138

ADJST-1138 Fixing the width for custody abroad offences page

---

server/services/prisonerService.ts

https://dsdmoj.atlassian.net/browse/ADJST-468

ADJST-468 Expand list of sentence types that counted as recalls

---

server/model/remand/remandViewModel.ts

https://dsdmoj.atlassian.net/browse/ADJST-614

ADJST-614 Fix the remand review table

---

server/model/viewModel.ts
server/views/pages/adjustments/view.njk

https://dsdmoj.atlassian.net/browse/ADJST-1190

ADJST-1190 Total Column Design changes - Display in table instead of <p>

---

helm_deploy/hmpps-adjustments/values.yaml

https://dsdmoj.atlassian.net/browse/ADJST-1260

ADJST-1260 Correct Helm files to read from the new repo.
